version: "2"
linters:
  enable:
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - unconvert
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    gocyclo:
      min-complexity: 15
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
