version: 2

project_name: rift

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: rift
    main: ./cmd/rift
    binary: rift
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildTime={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [ zip ]
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: riftdata
    name: rift
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"

homebrew_casks:
  - name: rift
    repository:
      owner: riftdata
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://riftdata.io"
    description: "Instant, copy-on-write database branches for Postgres"
    binaries:
      - rift

dockers_v2:
  - images:
      - "riftdata/rift"
      - "ghcr.io/riftdata/rift"
    tags:
      - "v{{ .Version }}"
      - latest
    dockerfile: docker/Dockerfile
    build_args:
      VERSION: "{{ .Version }}"
      COMMIT: "{{ .ShortCommit }}"
      BUILD_TIME: "{{ .Date }}"

announce:
  skip: true
