version: 2

project_name: rift

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: rift
    main: ./cmd/rift
    binary: rift
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildTime={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: rift
    name: rift
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"

homebrew_casks:
  - name: rift
    repository:
      owner: rift
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://riftdata.io"
    description: "Instant, copy-on-write database branches for Postgres"
    license: "Apache-2.0"
    install: |
      bin.install "rift"
    test: |
      system "#{bin}/rift", "--version"

dockers:
  - image_templates:
      - "riftdata/rift:{{ .Version }}-amd64"
      - "ghcr.io/riftdata/rift:{{ .Version }}-amd64"
    use: buildx
    dockerfile: docker/Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=COMMIT={{.ShortCommit}}"
      - "--build-arg=BUILD_TIME={{.Date}}"

  - image_templates:
      - "riftdata/rift:{{ .Version }}-arm64"
      - "ghcr.io/riftdata/rift:{{ .Version }}-arm64"
    use: buildx
    dockerfile: docker/Dockerfile
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=COMMIT={{.ShortCommit}}"
      - "--build-arg=BUILD_TIME={{.Date}}"

docker_manifests:
  - name_template: "riftdata/rift:{{ .Version }}"
    image_templates:
      - "riftdata/rift:{{ .Version }}-amd64"
      - "riftdata/rift:{{ .Version }}-arm64"

  - name_template: "riftdata/rift:latest"
    image_templates:
      - "riftdata/rift:{{ .Version }}-amd64"
      - "riftdata/rift:{{ .Version }}-arm64"

  - name_template: "ghcr.io/riftdata/rift:{{ .Version }}"
    image_templates:
      - "ghcr.io/riftdata/rift:{{ .Version }}-amd64"
      - "ghcr.io/riftdata/rift:{{ .Version }}-arm64"

  - name_template: "ghcr.io/riftdata/rift:latest"
    image_templates:
      - "ghcr.io/riftdata/rift:{{ .Version }}-amd64"
      - "ghcr.io/riftdata/rift:{{ .Version }}-arm64"

announce:
  skip: true
