version: 2

project_name: rift

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: rift
    main: ./cmd/rift
    binary: rift
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildTime={{.Date}}
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=zigcc-linux-amd64
          - CXX=zigcpp-linux-amd64
      - goos: linux
        goarch: arm64
        env:
          - CC=zigcc-linux-arm64
          - CXX=zigcpp-linux-arm64
      - goos: darwin
        goarch: amd64
        env:
          - CC=zigcc-darwin-amd64
          - CXX=zigcpp-darwin-amd64
      - goos: darwin
        goarch: arm64
        env:
          - CC=zigcc-darwin-arm64
          - CXX=zigcpp-darwin-arm64

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: riftdata
    name: rift
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
  extra_files:
    # Windows binary is uploaded by the separate release-windows job.
    # GoReleaser's extra_files allows it to be included in checksums
    # if it exists at release time, but it's uploaded separately.
    [ ]

homebrew_casks:
  - name: rift
    repository:
      owner: riftdata
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://riftdata.io"
    description: "Instant, copy-on-write database branches for Postgres"
    binaries:
      - rift

# Docker images are built and pushed by .github/workflows/docker.yml
# which uses docker/build-push-action with SBOM and provenance attestations.
# GoReleaser's dockers_v2 does not support BuildKit attestations, so Docker
# publishing is intentionally handled outside of GoReleaser to ensure all
# images on Docker Hub and GHCR have a software bill of materials and
# provenance attached.

announce:
  skip: true
