version: 2

project_name: rift

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: rift
    main: ./cmd/rift
    binary: rift
    env:
      - CGO_ENABLED=1
    # Linux only — macOS and Windows are built natively on their own CI runners
    # and uploaded to the release separately (see release.yml).
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildTime={{.Date}}
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=zigcc-linux-amd64
          - CXX=zigcpp-linux-amd64
      - goos: linux
        goarch: arm64
        env:
          - CC=zigcc-linux-arm64
          - CXX=zigcpp-linux-arm64

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: riftdata
    name: rift
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"

# Homebrew cask is updated by a post-release job after all platform
# binaries (including macOS) are uploaded. GoReleaser only builds Linux,
# so it cannot generate the cask itself.

# Docker images are built and pushed by .github/workflows/docker.yml
# which uses docker/build-push-action with SBOM and provenance attestations.

announce:
  skip: true
