#!/bin/sh

echo "Running fmt..."
gofmt -s -w .

echo "Running lint..."
if ! golangci-lint run; then
  echo "Lint failed"
  exit 1
fi

echo "Running tests..."
if ! go test -race -short ./...; then
  echo "Tests failed"
  exit 1
fi

echo "Pre-commit passed"
